### ISSUE TITLE
Gradle does not start building custom components (ui/component/*)

### ISSUE THREAD

**Issue by ndt080** [openremote/custom-project#6]
There is a custom application and a custom UI component package. Here is the structure
![Screenshot 2024-02-22 120939](https://github.com/openremote/custom-project/assets/68751397/10001168-6f49-492e-8ea5-8ce10aac5398)

Executing the command ``` ./gradlew clean installDist```, the build crashes.

The problem is that cradle starts building a custom application when the package of a custom component is not built.

![image](https://github.com/openremote/custom-project/assets/68751397/faf712e2-9ddb-415e-afe7-a38a0da719ad)

You can see that the `gradle installDist task` was completed in the package of the custom component, but the package was not built.

![image](https://github.com/openremote/custom-project/assets/68751397/46c228bb-1cf1-4d5c-a2d8-f19a2ea4f86b)

The root package.json contains an indication of ui/component as a workspace, and an additional indication of the order of workspaces has no effect

![image](https://github.com/openremote/custom-project/assets/68751397/fac79016-6452-4d8c-b0c8-872bf558c0e4)

**Comment by richturner** [comment]
Hi,

Sorry for the delay; I'll respond on the forum
